import "server-only";

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod/v3";

import {
  POSTING_PLATFORMS,
  type PostingPlatform,
} from "@/lib/platforms/capabilities";
import { withMcpTool } from "../withMcpTool";

type GeneratePostDraftArgs = {
  platform: PostingPlatform;
  topic: string;
  tone: "professional" | "casual" | "humorous" | "educational" | "promotional";
  max_length: number;
  additional_context?: string;
};

const PLATFORM_GUIDELINES: Record<PostingPlatform, string> = {
  linkedin:
    "LinkedIn: professional tone, 1-3 paragraphs, use relevant hashtags sparingly (3-5). No emojis overload.",
  tiktok:
    "TikTok: short, punchy caption under 300 chars. Hook in the first line. Trending hashtags welcome.",
  pinterest:
    "Pinterest: descriptive pin caption, include keywords naturally, 100-500 chars.",
  instagram:
    "Instagram: engaging caption, mix of storytelling and call-to-action, emoji-friendly, up to 2200 chars.",
  youtube:
    "YouTube: this becomes the video description. Front-load keywords in the first 2 lines, then detail, links, and chapters. Up to 5000 chars.",
  x: "X: 280 characters max. One sharp idea, no hashtag stuffing (0-2 hashtags).",
  facebook:
    "Facebook: conversational Page post, 1-2 short paragraphs, a question or call-to-action at the end.",
};

/**
 * Generates a post draft prompt that the client's own LLM can run.
 *
 * Plan gate: creator (ACTION_PLAN_GATE in entitlement.ts; monthly quota
 * enforced by the HOF: Creator 100 per month, Pro unlimited).
 * Tables touched: none (sampling is a client-side operation).
 *
 * This tool builds a structured prompt string and returns it so the
 * calling agent can generate the draft using its own inference budget.
 * Sharetopus pays zero AI credits.
 *
 * Auditing: we scrub `additional_context` from the audit row because
 * it can contain free-form user secrets or brand-confidential text.
 * Only `platform` and `topic` are persisted.
 */
export function registerGeneratePostDraft(server: McpServer): void {
  server.registerTool(
    "generate_post_draft",
    {
      title: "Generate Post Draft",
      description:
        "Generate a draft post using your AI assistant. Requires the Creator plan or higher (100 drafts per month on Creator, unlimited on Pro). The draft is generated by your client's LLM at no cost to your Sharetopus account.",
      inputSchema: {
        platform: z
          .enum(POSTING_PLATFORMS)
          .describe("Target platform for the draft"),
        topic: z.string().describe("Topic or theme for the post"),
        tone: z
          .enum([
            "professional",
            "casual",
            "humorous",
            "educational",
            "promotional",
          ])
          .optional()
          .default("professional")
          .describe("Tone of voice for the draft"),
        max_length: z
          .number()
          .int()
          .min(50)
          .max(3000)
          .optional()
          .default(500)
          .describe("Approximate max character count"),
        additional_context: z
          .string()
          .optional()
          .describe("Any extra instructions or brand guidelines"),
      },
      annotations: {
        title: "Generate Post Draft",
        readOnlyHint: true,
        openWorldHint: false,
      },
    },
    withMcpTool(
      "generate_post_draft",
      async (_ctx, args: GeneratePostDraftArgs) => {
        const draftPrompt = [
          `Write a ${args.tone} social media post for ${args.platform}.`,
          `Topic: ${args.topic}`,
          `Max length: ~${args.max_length} characters.`,
          PLATFORM_GUIDELINES[args.platform],
          args.additional_context
            ? `Additional context: ${args.additional_context}`
            : "",
          "",
          "Return ONLY the post text, no commentary or metadata.",
        ]
          .filter(Boolean)
          .join("\n");

        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(
                {
                  action: "draft_prompt",
                  platform: args.platform,
                  prompt: draftPrompt,
                  instructions:
                    "Use this prompt to generate the draft. Then pass the result to schedule_post when ready.",
                },
                null,
                2,
              ),
            },
          ],
          auditArgs: { platform: args.platform, topic: args.topic },
        };
      },
    ),
  );
}
